/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.co.ceiba.adn;
        

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;



@SpringBootApplication

public class App {
   
	

    public static void main(String[] args) {
    	SpringApplication.run(App.class, args);        
    }
}
